name: JMeter Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ☕ Install Java (required for JMeter)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download JMeter
        run: |
          curl -O https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          echo "JMETER_HOME=$(pwd)/apache-jmeter-5.6.3" >> $GITHUB_ENV

      - name: Run JMeter test plan
        run: |
          mkdir -p jmeter-results
          ${{ env.JMETER_HOME }}/bin/jmeter \
            -n \
            -t jmeter/test-plan.jmx \
            -l jmeter-results/results.jtl \
            -e -o jmeter-results/html-report

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: jmeter-results/html-report
