name: JMeter Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ☕ Install Java (required for JMeter)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download JMeter
        run: |
          curl -O https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          echo "JMETER_HOME=$(pwd)/apache-jmeter-5.6.3" >> $GITHUB_ENV

      - name: Run all JMeter test files
        run: |
          mkdir -p jmeter-results
          for file in $(find jmeter -name "*.jmx"); do
            test_name=$(basename "$file" .jmx)
            echo "Running test: $test_name"
            $JMETER_HOME/bin/jmeter \
              -n \
              -t "$file" \
              -l "jmeter-results/${test_name}.jtl" \
              -e -o "jmeter-results/${test_name}-report"
          done        

      - name: 📤 Upload all HTML reports
        uses: actions/upload-artifact@v4
        if: always()          # still upload even if a test fails
        with:
          name: jmeter-html-reports
          path: jmeter-results/**          # <-- matches what you created
